services:
  socket-proxy:
    image: tecnativa/docker-socket-proxy:latest
    container_name: docker_socket_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
      - POST=1
    restart: always

  monitor:
    build: .
    container_name: docker_resource_monitor
    ports:
      - "${APP_PORT:-5000}:5000"
    environment:
      - DOCKER_HOST=tcp://socket-proxy:2375
    depends_on:
      - socket-proxy
    pid: "host"
    restart: always
