services:
  monitor:
    build: .
    container_name: docker_resource_monitor
    ports:
      - "${APP_PORT:-5151}:5000"
    volumes:
      # Grants access to the host's Docker socket
      - /var/run/docker.sock:/var/run/docker.sock
    # Relies on the host network namespaces if you want psutil 
    # to evaluate direct system-level RAM and CPU parameters with less virtualization bias
    pid: "host"
    restart: always
